apiVersion: v1
kind: ServiceAccount
metadata:
  name: __LOAD_BALANCER_CONTROLLER_SERVICE_ACCOUNT__
  namespace: __LOAD_BALANCER_CONTROLLER_NAMESPACE__
  annotations:
    eks.amazonaws.com/role-arn: __LOAD_BALANCER_CONTROLLER_IRSA_ROLE_ARN__
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/part-of: terraformers-modernization
