package com.terraformers.modernization.analysis;

import java.util.List;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnMissingBean(AnalysisProvider.class)
public class FallbackAnalysisProvider implements AnalysisProvider {

    @Override
    public AnalysisResult analyze(AnalysisRequestContext context) {
        String terraformDraft = """
                # Terraformers local analysis fallback
                # projectId: %s
                # sourceBucket: %s
                # sourceKey: %s

                terraform {
                  required_version = ">= 1.5.0"
                }
                """.formatted(
                context.projectId(),
                context.sourceBucket(),
                context.sourceKey()
        ).strip();

        return new AnalysisResult(
                "local-fallback",
                terraformDraft,
                "Generated by the local fallback provider because no external analysis provider bean is active.",
                List.of("s3://" + context.sourceBucket() + "/" + context.sourceKey())
        );
    }
}
