import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../utils/api';
const labels = { PENDING: '분석 요청이 대기 중입니다.', RUNNING: 'AI가 아키텍처를 분석하고 있습니다.', SUCCEEDED: '분석이 완료되었습니다.', FAILED: '분석에 실패했습니다.' };
function ProjectDetailPage() {
  const { projectId } = useParams(); const [project, setProject] = useState(null); const [terraform, setTerraform] = useState(''); const [imageUrl, setImageUrl] = useState(''); const [error, setError] = useState(''); const objectUrlRef = useRef(null);
  useEffect(() => { let timer; let active = true; const load = async () => { try { const response = await api.get(`/api/projects/${projectId}`); if (!active) return; setProject(response.data); if (['PENDING', 'RUNNING'].includes(response.data.analysisStatus)) timer = setTimeout(load, 2000); } catch (err) { if (active) setError(err?.response?.data || err.message); } }; load(); return () => { active = false; clearTimeout(timer); }; }, [projectId]);
  useEffect(() => { let active = true; if (!project?.sourceFileId) { setImageUrl(''); return undefined; } api.get(`/api/projects/${projectId}/source-image`, { responseType: 'blob' }).then((response) => { if (!active) return; if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current); objectUrlRef.current = URL.createObjectURL(response.data); setImageUrl(objectUrlRef.current); }); return () => { active = false; }; }, [projectId, project?.sourceFileId]);
  useEffect(() => { let active = true; if (!project?.resultFileId) { setTerraform(''); return undefined; } api.get(`/api/projects/${projectId}/terraform/main.tf`).then((response) => { if (active) setTerraform(response.data?.content || ''); }); return () => { active = false; }; }, [projectId, project?.resultFileId]);
  useEffect(() => () => { if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current); }, []);
  if (error) return <p role="alert" className="error">{error}</p>; if (!project) return <p>프로젝트를 불러오는 중입니다.</p>;
  return <section className="page-stack"><Link to="/projects">내 프로젝트 목록으로 돌아가기</Link><h1>{project.displayName}</h1><p><strong>{project.analysisStatus || 'NO_ANALYSIS'}</strong> {labels[project.analysisStatus]}</p>{imageUrl && <img src={imageUrl} alt={`${project.displayName} architecture`} style={{ objectFit: 'contain', maxWidth: '100%', height: 'auto', maxHeight: 640 }} />}{project.failureReason && <p role="alert" className="error">{project.failureReason}</p>}<p>{project.analysisSummary}</p>{project.detectedComponents?.length > 0 && <p><strong>구성요소:</strong> {project.detectedComponents.join(', ')}</p>}{project.detectedRelationships?.length > 0 && <p><strong>관계:</strong> {project.detectedRelationships.join(', ')}</p>}{project.warnings?.length > 0 && <p><strong>Warnings:</strong> {project.warnings.join(', ')}</p>}{project.resultFileId && <pre className="terraform-code"><code>{terraform}</code></pre>}</section>;
}
export default ProjectDetailPage;
