apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terraformers-local

resources:
  - ../../base

images:
  - name: public.ecr.aws/example/terraformers-backend
    newName: terraformers-backend
    newTag: local-stub

patches:
  - path: backend-configmap-patch.yaml
  - path: backend-deployment-patch.yaml
